<a href="https://colab.research.google.com/github/sirdrigar/data-science-bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
np.__version__

'1.21.6'

### Norma wektora, długość wektora w $R^2$

In [10]:
v1 = np.array([0, 4])
v1

array([0, 4])

In [11]:
np.linalg.norm(v1)

4.0

##Norma euklidesowa w $R^n$

In [12]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

##Odległość dwóch punktów na płaszczyźnie

In [13]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

##Odległość dwóch punktów w przestrzeni $R^n$

In [14]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

##Mnożenie macierzy

###Przykład 1

In [20]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [28]:
# mnożenie
#X @ Y
z = np.dot(X, Y)
z

array([[ 2],
       [-6]])

In [29]:
z.shape

(2, 1)

### Przykład 2

In [30]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])

print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [31]:
z = X @ Y
z

array([[13,  9, -4],
       [ 6,  2, -1]])

In [32]:
z.shape

(2, 3)

##Wyznacznik macierzy

In [36]:
A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10

##Ślad macierzy

In [37]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

##Macierz jednostkowa

Macierz jednostkowa - macierz kwadratowa, w której spółczynniki na przekątnej są równe 1

In [38]:
np.eye(5, dtype='int') # generuje macierz jednostkową stopnia n

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

##Macierz odwrotna

Takie macierze gdzie A @ B i B @ A muszą dawać macierz jednostkową

In [39]:
A

array([[ 2,  4],
       [-1,  3]])

In [42]:
B = np.linalg.inv(A) #wyznaczenie macierzy odwrotnej
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [46]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [48]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

##Macierz transponowana

Zamiana wierszy na kolumny i kolumn na wiersze

In [49]:
A

array([[ 2,  4],
       [-1,  3]])

In [51]:
#np.transpose(A)
A.T

array([[ 2, -1],
       [ 4,  3]])

##Rozwiązywanie układów rónań

Jeśli macierz układu A jest macierzą kwadratową, to oznaczoność układu jest równoważna jej odwracalności, tzn.

                      AX = B
                      A^-1AX = A^-1B
                      X = A^-1B

In [67]:
# 2x + 4y = 10      2 4    x   10
# x - y = -1        1 -1   y    -1
# x =1
#y = 2
A = np.array([[2, 4], [1, -1]])
B = np.array([[10],[-1]])
print(A, '\n')
print(B)

[[ 2  4]
 [ 1 -1]] 

[[10]
 [-1]]


In [72]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.1667,  0.6667],
       [ 0.1667, -0.3333]])

In [73]:
A @ A_inv

array([[1., 0.],
       [0., 1.]])

In [74]:
#np.linalg.inv(A) @ B  <- odwrotnosc A @ B
X = A_inv @ B
X  # x = 1, y =2

array([[1.],
       [2.]])