<a href="https://colab.research.google.com/github/sirdrigar/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Podstawy

In [1]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [4]:
x = np.array([1, 3])
x

array([1, 3])

In [5]:
print(x)

[1 3]


In [6]:
type(x)

numpy.ndarray

In [7]:
x.ndim

1

In [8]:
x.shape

(2,)

In [9]:
x.size

2

In [10]:
x.dtype

dtype('int64')

In [11]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [12]:
x.dtype

dtype('float64')

2D Array

In [13]:
x =np.array([[1,2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [14]:
x.ndim

2

In [15]:
x.shape

(2, 2)

In [16]:
x = np.array([[1, 2, 4], [4,2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [17]:
x.shape

(2, 3)

3D Array

In [24]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]],

     [[3, 2, 1],
      [4, 3, 2]]
     ]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [25]:
x.ndim

3

In [26]:
x.shape

(3, 2, 3)

##Typy danych

In [27]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [28]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [29]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [30]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [31]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [32]:
A = np.array([1.0, 2.3, 3.3], dtype='int')
A.dtype

dtype('int64')

In [33]:
A

array([1, 2, 3])

In [34]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [37]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

##Tworzenie tablic

In [39]:
np.zeros(shape=(4, 10), dtype ='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [40]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [42]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [43]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [47]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [49]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [51]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [53]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [54]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

##Podstawowe operacje na tablicach

In [57]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [58]:
A + B

array([6, 0, 7, 4])

In [59]:
A - B

array([0, 2, 1, 0])

In [60]:
A * B

array([ 9, -1, 12,  4])

In [63]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [67]:
np.add(A, B)

array([6, 0, 7, 4])

In [68]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [69]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [70]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [64]:
A + 3

array([6, 4, 7, 5])

In [65]:
2 * A

array([6, 2, 8, 4])

In [66]:
A + 3 * B

array([12, -2, 13,  8])

In [76]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [77]:
X * Y

array([[6, 0],
       [2, 0]])

In [79]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [80]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [81]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [82]:
X @ Y

array([[  3,   6],
       [-12,   0]])