<a href="https://colab.research.google.com/github/sirdrigar/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Podstawy

In [1]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [4]:
x = np.array([1, 3])
x

array([1, 3])

In [5]:
print(x)

[1 3]


In [6]:
type(x)

numpy.ndarray

In [7]:
x.ndim

1

In [8]:
x.shape

(2,)

In [9]:
x.size

2

In [10]:
x.dtype

dtype('int64')

In [11]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [12]:
x.dtype

dtype('float64')

2D Array

In [13]:
x =np.array([[1,2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [14]:
x.ndim

2

In [15]:
x.shape

(2, 2)

In [16]:
x = np.array([[1, 2, 4], [4,2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [17]:
x.shape

(2, 3)

3D Array

In [24]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]],

     [[3, 2, 1],
      [4, 3, 2]]
     ]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [25]:
x.ndim

3

In [26]:
x.shape

(3, 2, 3)

##Typy danych

In [27]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [28]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [29]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [30]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [31]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [32]:
A = np.array([1.0, 2.3, 3.3], dtype='int')
A.dtype

dtype('int64')

In [33]:
A

array([1, 2, 3])

In [34]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [37]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

##Tworzenie tablic

In [38]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])