<a href="https://colab.research.google.com/github/sirdrigar/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Podstawy

In [1]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

1D Array

In [4]:
x = np.array([1, 3])
x

array([1, 3])

In [5]:
print(x)

[1 3]


In [6]:
type(x)

numpy.ndarray

In [7]:
x.ndim

1

In [8]:
x.shape

(2,)

In [9]:
x.size

2

In [10]:
x.dtype

dtype('int64')

In [11]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [12]:
x.dtype

dtype('float64')

2D Array

In [13]:
x =np.array([[1,2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [14]:
x.ndim

2

In [15]:
x.shape

(2, 2)

In [16]:
x = np.array([[1, 2, 4], [4,2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [17]:
x.shape

(2, 3)

3D Array

In [18]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]],

     [[3, 2, 1],
      [4, 3, 2]]
     ]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [19]:
x.ndim

3

In [20]:
x.shape

(3, 2, 3)

##Typy danych

In [21]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [22]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [23]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [24]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [25]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [26]:
A = np.array([1.0, 2.3, 3.3], dtype='int')
A.dtype

dtype('int64')

In [27]:
A

array([1, 2, 3])

In [28]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [29]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

##Tworzenie tablic

In [30]:
np.zeros(shape=(4, 10), dtype ='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [31]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [33]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [36]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [37]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [39]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [40]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [41]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [44]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

##Podstawowe operacje na tablicach

In [45]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [46]:
A + B

array([6, 0, 7, 4])

In [47]:
A - B

array([0, 2, 1, 0])

In [48]:
A * B

array([ 9, -1, 12,  4])

In [49]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [50]:
np.add(A, B)

array([6, 0, 7, 4])

In [51]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [52]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [53]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [54]:
A + 3

array([6, 4, 7, 5])

In [55]:
2 * A

array([6, 2, 8, 4])

In [56]:
A + 3 * B

array([12, -2, 13,  8])

In [57]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [58]:
X * Y

array([[6, 0],
       [2, 0]])

In [59]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [60]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [61]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [62]:
X @ Y

array([[  3,   6],
       [-12,   0]])

##Generowanie liczb pseudolosowych

In [69]:
np.random.seed(0)

In [70]:
np.random.randn()

1.764052345967664

In [71]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [72]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [73]:
np.random.rand()

0.1965823616800535

In [74]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [75]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [76]:
np.random.randint(10)

3

In [78]:
np.random.randint(low=10, high=101)

56

In [79]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [81]:
np.random.choice([4, 2, 1, 3, 5])

4

In [82]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [84]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
np.random.shuffle(data)

In [86]:
data

array([6, 9, 1, 5, 0, 7, 3, 4, 8, 2])

##Podstawowe funkcje

In [87]:
np.exp(1)

2.718281828459045

In [88]:
np.sqrt(9)

3.0

In [89]:
np.all([2, 3, 1])

True

In [94]:
np.any([0, 0, 0])

False

In [96]:
bool(1.3)

True

In [98]:
A = np.random.rand(5)
A

array([0.58127287, 0.88173536, 0.69253159, 0.72525428, 0.50132438])

In [101]:
A[np.argmax(A)]

0.8817353618548528

In [102]:
A[np.argmin(A)]

0.5013243819267023

In [103]:
np.argsort(A)

array([4, 0, 2, 3, 1])

In [104]:
np.max(A)

0.8817353618548528

In [105]:
np.min(A)

0.5013243819267023

In [106]:
np.mean(A)

0.676423697262964

In [107]:
np.median(A)

0.6925315900777659

In [108]:
np.std(A)

0.13000786074672221

##Indeksowanie, Wycinanie

In [110]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#A[idx], A[start:stop], A[:stop], A[start:]

In [113]:
A[2]

2

In [114]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [115]:
A[:2]

array([0, 1])

In [116]:
A[[0,2]]

array([0, 2])

In [117]:
A[-1]

19

In [118]:
A[10:15]

array([10, 11, 12, 13, 14])

In [119]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [125]:
A[1] # cut second row

array([5, 6, 7, 8, 9])

In [126]:
A[:, 0] # cut first column

array([ 0,  5, 10, 15])

In [127]:
A[:, -1] # cut last column

array([ 4,  9, 14, 19])

In [129]:
A[1, 3] # cut value from 2nd row and 4th column

8

In [152]:
A[2:4, 1:3]  #  rows from:to (from 0, to -1) : cols from:to (from 0, to -1)

array([[11, 12],
       [16, 17]])

In [160]:
A[1:2] # same as A[1] - cut 2nd row

array([[5, 6, 7, 8, 9]])

In [163]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

###Iteracja po tablicach